server:
  port: 8484
  servlet:
    session:
      timeout: 8h

spring:
  application:
    name: MinecraftManager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minecraft_manager_ltd?useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    username: admin@163.com
    password: 123456789
    port: 465
    host: smtp.163.com

# ========== self config ==========
minecraft:
  rcon:
    host: 127.0.0.1
    port: 25575
    password: 123456
    wlcmd: whitelist
    heart-time: 600
    test-cmd: ping
    add-cmd: login whitelist
email:
  enable: false
